### PR TITLE
add gene id as column output by junctions annotate

### PR DESCRIPTION
**Pull request by yang-yangfeng**
addresses #76

### CODE REVIEW

**Comment by yanyangfeng** [comment]
"In file included from /usr/lib/gcc/x86_64-linux-gnu/4.6/../../../../include/c++/4.6/array:35:
/usr/lib/gcc/x86_64-linux-gnu/4.6/../../../../include/c++/4.6/bits/c++0x_warning.h:32:2: error: This file requires compiler and library support for the upcoming ISO C++ standard, C++0x. This support is currently experimental, and must be enabled with the -std=c++0x or -std=gnu++0x compiler options."

I feel like the tests might be failing because of the compiler used in the travis environment? This commit seems to be compiling and working fine on my macbook. It seems to be complaining about std::array, which shouldn't be anything esoteric. Or is there something funky with how I'm doing my includes? Any ideas @gatoravi?

**Comment by yanyangfeng** [comment]
Hi @gatoravi, would you know anything about how to modify the travis CI environment?

**Comment by gatoravi** [comment]
The compiler error that showed up previously doesn't seem to show up anymore. However there are differences in the number of donors and acceptors between the test results and the expected test output. @yang-yangfeng any idea why this might be? Do you expect these numbers to change with these changes for some reason?

**Comment by yang-yangfeng** [comment]
Yeah it looks like I at some point updated some the test files (#94), but this was after this PR was made - so I guess when the now updated cis-splice-effects identify got merged into this PR, the output changed but the tests did not?

**Comment by gatoravi** [comment]
Ok, that does make sense. With a few more tweaks, this pull-request looks good!

**Pull request merged**
